application: sqmager
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: /
  script: convert.py

- url: /convert
  script: convert.py

- url: /upload
  script: convert.py

- url: /image
  script: convert.py
