application: swage
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: upload.py

- url: /swage
  script: swage.py
